//module.js

exports.questions = function() {
    let ar_questions = [
        "Can you tell me about a time when you consulted others when making important project decisions?",
        "Describe a leadership role of yours outside of work. Why did you commit your time to it? How did you feel about it?",
        "Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?",
        "Describe a project or idea, not necessarily your own, that was implemented primarily because of your efforts. What was your role? What was the outcome?",
        "Describe a recent unpopular decision you made. How was it received? How did you handle it?",
        "Describe a situation in which you had to arrive at a compromise or help others to compromise. What was your role? What steps did you take? What was the result?",
        "Describe a situation in which you recognized a potential problem as an opportunity. What did you do? What was the result? What, if anything, do you wish you had done differently?",
        "Describe a situation that required you to do a number of things at the same time. How did you handle it? What was the result?",
        "Describe a situation where others you were working with on a project disagreed with your ideas. What did you do?",
        "Describe a situation where you found yourself dealing with someone who did not like you. How did you handle it?",
        "Describe a situation where you had a conflict with another individual, and how you dealt with it. What was the outcome? How did you feel about it?",
        "Describe a time when it was especially important to make a good impression on a client. How did you go about doing so?",
        "Describe a time when you convinced a resistant customer to utilize your services.",
        "Describe a time when you had to interact with a difficult client. What was the situation, and how did you handle it?",
        "Describe a time when you saw some problem and took the initiative to correct it rather than waiting for someone else to do it.",
        "Describe a time when you struggled to build a relationship with someone important. How did you eventually overcome that?",
        "Describe a time when you were not only responsible for leading a team of people, but also for doing the same job as your team members? How did you balance your time?",
        "Describe a time when you were the resident technical expert. What did you do to make sure everyone was able to understand you?",
        "Describe a time when your team or company was undergoing some change. How did that affect you, and how did you adapt?",
        "Describe a time you took a leadership position when you did not have the title of a leader.",
        "Describe how you would handle a busy situation where three people are waiting for help from you.",
        "Describe the project or situation that best demonstrates your analytical abilities. What was your role?",
        "Describe what Human Resource means to you.",
        "Discuss a time when your integrity was challenged. How did you handle it?",
        "Do you know our CEO? How do you pronounce his name?",
        "Do you think you'll reach a point where you storm off the floor and never return?",
        "Explain a time when you were not able to meet a deadline?",
        "Give a specific example of a policy you conformed to with which you did not agree. Why?",
        "Give an example of a challenge you faced in the workplace, and how you overcame it.",
        "Give an example of a time you handled conflict in the workplace.",
        "Give an example of a time you went well out of your way to ensure a customer received the best possible service from you and organization. What was their reaction?",
        "Give an example of team leading in past employment",
        "Give an example of when you had to work with someone who was difficult to get along with. How did you handle it? How did the relationship progress?",
        "Give me an example of a business decision you made that you ultimately regretted. What happened?",
        "Give me an example of a time when you did not meet a clien's expectation. What happened, and how did you attempt to rectify the situation?",
        "Give me an example of a time when you had to be quick in coming to a decision. What obstacles did you face?",
        "Give me an example of a time when you had to explain something fairly complex to a frustrated client. How did you handle this delicate situation?",
        "Give me an example of a time when you had to plan a project or a large piece of work.",
        "Give me an example of a time when you had to think on your feet in order to delicately extricate yourself from a difficult or awkward situation.",
        "Give me an example of a time when you motivated others.",
        "Give me an example of a time when you showed initiative.",
        "Give me an example of a time when you were 75% of the way through a project, and you had to pivot strategy, how were you able to make that into a success story?",
        "Give me an example of a time when you were able to successfully communicate with another person even when that individual may not have personally liked you or vice versa.",
        "Give me an example of a time when you were able to successfully persuade someone to see things your way at work.",
        "Give me an example of a time you discovered an error that has been overlooked by a colleague. What did you do? What was the outcome?",
        "Give me an example of a time you faced a conflict while working on ateam. How did you handle that?",
        "Give me an example of a time you managed numerous responsibilities. How did you handle that?",
        "Give me an example of a time you were able to be creative with your work. What was exciting or difficult about it?",
        "Give me an example of an important career goal that you set yourself and tell me how you reached it. What obstacles did you encounter? How did you overcome the obstacles?",
        "Give me an example of something you tried to accomplish but failed.",
        "Give me an example of when someone brought you a new idea that was odd or unusual. What did you do?",
        "Give me an example of when you took a risk and it failed.",
        "Give me an example of your creativity?",
        "Have you ever had to “sell” an idea to your co-workers? How did you do it?",
        "How do you define success?",
        "How do you detect whether or not a word is a palindrome?",
        "How do you find the time to stay inspired, acquire new knowledge, and innovate in your work?",
        "How do you motivate yourself?",
        "How do you persuade people?",
        "How do you prioritize projects and tasks when scheduling your time?",
        "How do you resonate with our principle, Are right, a lot?",
        "How have you gone about setting short term goals and long term goals for yourself or your team? What steps did you take along the way to keep yourself accountable?",
        "How have you handled a situation in the past where your client has changed the brief or changed the goalposts?",
        "How was your transition from high school to university? Did you face any particular problems? How did you handle them?",
        "How would you deal with an angry customer?",
        "How would you introduce us in an elevator pitch?",
        "How would you solve problems if you were from Mars?",
        "How would you tell a customer what Wi-Fi is?",
        "If your direct manager was instructing you to do something you disagreed with, how would you handle it?",
        "Provide an example of how you explained a technical concept to a client or coworker lacking your technical expertise.",
        "Should we sell private label cleaning products?",
        "Sometimes it’s just not possible to get everything on your to-do list done. Tell me about a time your responsibilities got a little overwhelming. What did you do?",
        "Talk about a time when you had to work closely with someone whose personality was very different from yours.",
        "Tell me a challenge you had where the best way forward was not clear-cut.",
        "Tell me a time when you earned trust of a group.",
        "Tell me about a business situation when you felt honesty was inappropriate. Why? What did you do?",
        "Tell me about a particular work-related setback you have faced. How did you deal with it?",
        "Tell me about a problem that you have solved in a unique or unusual way. What was the outcome?",
        "Tell me about a professional goal that you set that you did not reach. How did it make you feel?",
        "Tell me about a project that you planned. How did your organize and schedule the tasks?",
        "Tell me about a project you initiated. What did you do? Why? What was the outcome? Were you happy with the result?",
        "Tell me about a situation in which you have had to adjust to changes over which you had no control. How did you handle it?",
        "Tell me about a situation where you had to solve a difficult problem. What did you do? What was the outcome?",
        "Tell me about a successful presentation you gave and why you think it was a hit.",
        "Tell me about a team project when you had to take charge of the project? What did you do? What was the result?",
        "Tell me about a time in which you had to use your written communication skills in order to get an important point across.",
        "Tell me about a time that you were confused by a customer’s request. What steps did you take to clarify things?",
        "Tell me about a time when you coached someone.",
        "Tell me about a time when you delegated a project effectively.",
        "Tell me about a time when you experienced a loss for doing what is right. How did you react?",
        "Tell me about a time when you had to adjust to a colleague’s working style in order to complete a project or achieve your objectives.",
        "Tell me about a time when you had to analyze information and make a recommendation. What kind of thought process did you go through?",
        "Tell me about a time when you had to deal with a poor performer on your team.",
        "Tell me about a time when you had to make a decision without all the information you needed. How did you handle it?",
        "Tell me about a time when you had to rely on written communication to get your ideas across to your team.",
        "Tell me about a time when you had to settle a dispute between team members. How did you go about identifying the issues? What was the result?",
        "Tell me about a time when you had to work on a team that did not get along. What happened? What role did you take? What was the result?",
        "Tell me about a time when you made sure a customer was pleased with your service.",
        "Tell me about a time when you observed two business opportunities to improve ROI, and how did you determine that they were connected.",
        "Tell me about a time when you worked under close supervision or extremely loose supervision. How did you handle that?",
        "Tell me about a time when you worked with a colleague who was not doing their share of the work. How did you handle it?",
        "Tell me about a time when your initiative caused a change to occur.",
        "Tell me about a time where you overcame an obstacle and delivered results.",
        "Tell me about a time where you thought of a clever new way to save money for the company.",
        "Tell me about a time you failed. How did you deal with this situation?",
        "Tell me about a time you had to be very strategic in order to meet all your top priorities.",
        "Tell me about a time you had to work hard to please a client.",
        "Tell me about a time you have inherited a customer. What steps did you take to establish rapport with them? What did you do to gain their trust?",
        "Tell me about a time you needed to get information from someone who was not very responsive. What did you do?",
        "Tell me about a time you set a goal for yourself. How did you go about ensuring that you would meet your objective?",
        "Tell me about a time you were dissatisfied in your work. What could have been done to make it better?",
        "Tell me about a time you were under a lot of pressure. What was going on, and how did you get through it?",
        "Tell me about the first job you’ve ever had. What did you do to learn the ropes?",
        "Tell me about the most difficult interaction you had at work.",
        "Tell me about your previous success in building a customer base from a standing start. What steps did you take?",
        "Tell me about your proudest professional accomplishment.",
        "Tell me about yourself?",
        "Tell the story of the last time you had to apologize to someone.",
        "Tell us about our product categories.",
        "Walk us through a time when you helped a customer through a difficult process and what that looked like.",
        "Was there a time that I failed at work and corrected it?",
        "Was there a time that I failed at work?",
        "We all make mistakes we wish we could take back. Tell me about a time you wish you had handled a situation differently with a colleague.",
        "What about important clients, or complex or sensitive customer relationships?",
        "What are three things your former manager would like you to improve on?",
        "What are you looking for?",
        "What are you looking to make?",
        "What are you Making Now?",
        "What are your greatest professional strengths?",
        "What are your long term career goals?",
        "What are your salary requirements?",
        "What are your weaknesses?",
        "What do you know about the company?",
        "What do you know about us?",
        "What has been the best idea you have come up with during your professional career?",
        "What has been the most stressful situation you have ever found yourself in at work? How did you handle it?",
        "What has been your greatest leadership achievement in a professional environment? Talk through the steps you took to reach it.",
        "What have been the greatest obstacles you have faced in building/growing a team?",
        "What have you done in the past to prevent a situation from becoming too stressful for you or your colleagues to handle?",
        "What have you found to be the difficult part of being a member, not leader, of a team? How did you handle this?",
        "What is the most difficult decision you have ever had to make at work? How did you arrive at your decision? What was the result?",
        "What is the most difficult situation you have ever faced in your life? How did you handle it?",
        "What is the toughest group that you have ever had to lead? What were the obstacles? How did you handle the situation?",
        "What is the worst mistake you ever made?",
        "What is your biggest achievement?",
        "What is your greatest professional achievement?",
        "What is your greatest sales-related achievement to date? What steps led to the final outcome?",
        "What is your ideal job at this stage in your career?",
        "What makes you the best candidate for the position?",
        "What obstacles or difficulties have you ever faced in communicating your ideas to a manager?",
        "What process do you use to check that you have the right details from a customer?",
        "What steps do you follow to study a problem before making a decision? Why?",
        "What was the biggest mistake you have made when delegating work as part of a team project?",
        "What was the most stressful professional negotiation you have been involved in? How did you handle it?",
        "What would you do if somehow you misdirected 10,000 units of something?",
        "What would you do if you found out that your closest friend at work was stealing?",
        "What would you do if you saw someone being unsafe at work?",
        "What, in your opinion, are the key ingredients in guiding and maintaining successful business relationships? Give me examples of how you have made them work for you.",
        "What's most important to you in your career?",
        "When has a project or event you organized not gone according to plan? What happened? How did you feel?",
        "When have you brought an innovative idea into your team? How was it received?",
        "When have you chosen to communicate a particular message in person as opposed to via email even though the email channel would have been a lot faster?",
        "When have you ever found yourself in a competitive situation professionally? How did you handle it?",
        "When have you ever gone out on a limb to defend a customer? What happened?",
        "When have you had to deal with an irate customer? What did you do? How did the situation end up?",
        "When have you had to present to a group of people with little or no preparation? What obstacles did you face? How did you handle them?",
        "When have you seen your tenacity or resilience really pay off in a professional setting? What was the outcome?",
        "When have you used your fact-finding skills to solve a problem?",
        "When was the last time you thought “outside the box” and how did you do it? Why?",
        "When you are working with a large number of customers, it is tricky to deliver excellent service to them all. How do you go about prioritizing your customer's needs?",
        "Where do you see yourself in five years?",
        "Which Amazon leadership principle do you resonate most with?",
        "Who was your most difficult customer?",
        "Why a want to work for us?",
        "Why are you keen to join us?",
        "Why did you leave, or why are you leaving, your job?",
        "Why should we hire you?",
        "Would you tell on a employee for stealing"
    ];
    
    return ar_questions;
}

exports.greeting = function() {
    let ar_greeting = [
        "Goodbye, thanks for using Interview Training",
        "Ok, I hope you've enjoyed the session",
        "Bye! I hope to see you later",
        "Ok, Talk to you later!",
        "Bye bye! stay tuned!",
        "Ok, I look forward to our next meeting",
        "Sure. It was nice seeing you",
        "No problem. Have a nice day!",
        "Ok. Have a good day!",
        '<lang xml:lang="es-ES">Adios.</lang>and don\'t forget to practice!',
        '<lang xml:lang="it-IT">Ciao.</lang>and thanks for using this skill!',
        '<lang xml:lang="fr-FR">Au revoir.</lang>I hope to see you soon!',
    ];
    
    return ar_greeting;
}